import { useState, type ReactNode } from "react";
import {
  Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3,
  Bell, BriefcaseBusiness, Building2, CalendarDays, Check, ChevronDown, ChevronLeft,
  ChevronRight, CircleAlert, ClipboardCheck, Clock3, Download, FileBarChart, FileCheck2,
  FileText, Filter, Gauge, GitCompareArrows, HelpCircle, History, Inbox, LayoutDashboard,
  Menu, MoreHorizontal, PanelLeftClose, PanelLeftOpen, Plus, RefreshCw, Search, Settings2,
  ShieldAlert, SlidersHorizontal, TrendingDown, TrendingUp, Upload, UserRound, Users, X,
  type LucideIcon,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";

type View = "dashboard" | "dossiers" | "dossier" | "portfolio" | "collecte" | "alertes" | "comparaison" | "rapports";
type Tone = "neutral" | "success" | "warning" | "danger" | "info";

const dossiers = [
  { id: "DD-2026-084", name: "Atlas Microfinance", type: "Institution de microfinance", amount: "18,5 M MAD", stage: "Analyse", risk: "B+", progress: 72, update: "Aujourd’hui, 09:42", owner: "S. El Amrani", tone: "warning" as Tone },
  { id: "DD-2026-081", name: "Nova Industrie", type: "TPME", amount: "7,2 M MAD", stage: "Avis", risk: "A-", progress: 88, update: "Hier, 16:20", owner: "N. Berrada", tone: "success" as Tone },
  { id: "DD-2026-079", name: "Al Omrane Services", type: "PME", amount: "12,0 M MAD", stage: "Questionnaire", risk: "—", progress: 46, update: "17 sept. 2026", owner: "Y. Idrissi", tone: "info" as Tone },
  { id: "DD-2026-073", name: "Tamwil Coopérative", type: "Coopérative financière", amount: "5,8 M MAD", stage: "Décision", risk: "B", progress: 96, update: "16 sept. 2026", owner: "L. Alaoui", tone: "danger" as Tone },
  { id: "DD-2026-069", name: "Sahara Agro", type: "TPME", amount: "9,4 M MAD", stage: "Collecte", risk: "—", progress: 31, update: "15 sept. 2026", owner: "M. Tazi", tone: "neutral" as Tone },
];

const alerts = [
  { client: "Atlas Microfinance", label: "Ratio PAR30 au-dessus du seuil", metric: "5,8 % > 5,0 %", severity: "Critique", date: "18 sept. 2026", tone: "danger" as Tone },
  { client: "Sahara Agro", label: "Données trimestrielles manquantes", metric: "Retard de 12 jours", severity: "Élevée", date: "17 sept. 2026", tone: "warning" as Tone },
  { client: "Tamwil Coopérative", label: "Baisse de la marge opérationnelle", metric: "−2,4 pts", severity: "Élevée", date: "16 sept. 2026", tone: "warning" as Tone },
  { client: "Nova Industrie", label: "Garantie à renouveler", metric: "Échéance dans 21 j", severity: "Moyenne", date: "15 sept. 2026", tone: "info" as Tone },
];

const nav: { group?: string; items: { id: View; label: string; icon: LucideIcon }[] }[] = [
  { items: [{ id: "dashboard", label: "Tableau de bord", icon: LayoutDashboard }] },
  { group: "PORTEFEUILLE", items: [{ id: "portfolio", label: "Clients", icon: Users }, { id: "portfolio", label: "Financements", icon: BriefcaseBusiness }] },
  { group: "DUE DILIGENCE", items: [{ id: "dossiers", label: "Dossiers", icon: ClipboardCheck }] },
  { group: "SUIVI", items: [{ id: "portfolio", label: "Suivi du portefeuille", icon: Activity }, { id: "collecte", label: "Collecte des données", icon: Inbox }, { id: "alertes", label: "Alertes & covenants", icon: ShieldAlert }, { id: "comparaison", label: "Comparaison", icon: GitCompareArrows }] },
  { group: "REPORTING", items: [{ id: "rapports", label: "Rapports", icon: FileBarChart }, { id: "rapports", label: "Benchmarking", icon: BarChart3 }] },
];

function Status({ children, tone = "neutral" }: { children: ReactNode; tone?: Tone }) {
  return <span className={cn("inline-flex items-center gap-1 rounded px-2 py-1 text-xs font-semibold", tone === "success" && "bg-success/10 text-success", tone === "warning" && "bg-warning/15 text-warning-foreground", tone === "danger" && "bg-danger-soft text-destructive", tone === "info" && "bg-info-soft text-primary", tone === "neutral" && "bg-muted text-muted-foreground")}>{children}</span>;
}

function Panel({ children, className }: { children: ReactNode; className?: string }) {
  return <section className={cn("rounded-lg border border-border bg-card shadow-[0_1px_2px_oklch(0.25_0.02_240/0.04)]", className)}>{children}</section>;
}

function PanelTitle({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) {
  return <div className="flex items-start justify-between gap-4 border-b border-border px-5 py-4"><div><h2 className="text-[15px] font-semibold text-foreground">{title}</h2>{subtitle && <p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>;
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: ReactNode }) {
  return <div className="mb-6 flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div>{eyebrow && <p className="mb-1 text-xs font-bold uppercase text-primary">{eyebrow}</p>}<h1 className="text-2xl font-bold text-foreground">{title}</h1><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>{action}</div>;
}

function Metric({ label, value, detail, icon: Icon, tone = "neutral", onClick }: { label: string; value: string; detail: string; icon: LucideIcon; tone?: Tone; onClick?: () => void }) {
  return <button onClick={onClick} className="group min-h-32 w-full rounded-lg border border-border bg-card p-4 text-left shadow-[0_1px_2px_oklch(0.25_0.02_240/0.04)] transition hover:border-primary/40 hover:shadow-sm"><div className="flex items-start justify-between"><span className={cn("flex size-9 items-center justify-center rounded-md", tone === "danger" ? "bg-danger-soft text-destructive" : tone === "warning" ? "bg-warning/15 text-warning-foreground" : tone === "success" ? "bg-success/10 text-success" : "bg-info-soft text-primary")}><Icon className="size-4" /></span><ChevronRight className="size-4 text-muted-foreground opacity-0 transition group-hover:opacity-100" /></div><p className="mt-4 text-2xl font-bold">{value}</p><p className="mt-1 text-sm font-medium">{label}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></button>;
}

function Dashboard({ go }: { go: (v: View) => void }) {
  return <><PageHeader title="Bonjour, Samira" description="Voici les priorités de votre équipe pour le vendredi 18 septembre." action={<div className="flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-4" /> Période active : T2 2026</div>} />
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
      <Metric label="Dossiers à traiter" value="15" detail="3 ajoutés cette semaine" icon={ClipboardCheck} tone="info" onClick={() => go("dossiers")} />
      <Metric label="Soumissions attendues" value="9" detail="dont 4 en retard" icon={Clock3} tone="warning" onClick={() => go("collecte")} />
      <Metric label="Alertes actives" value="12" detail="2 critiques à examiner" icon={AlertTriangle} tone="danger" onClick={() => go("alertes")} />
      <Metric label="Clients sous suivi" value="124" detail="Exposition : 684,2 M MAD" icon={Building2} tone="success" onClick={() => go("portfolio")} />
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]">
      <Panel><PanelTitle title="File de travail" subtitle="Dossiers nécessitant votre intervention" action={<Button variant="ghost" size="sm" onClick={() => go("dossiers")}>Tout afficher <ArrowRight /></Button>} />
        <div className="divide-y divide-border">
          {[["6", "Dossiers à compléter", "Informations ou pièces manquantes", "warning"], ["4", "Prêts pour l’analyse", "Données validées et questionnaire terminé", "info"], ["3", "En attente d’avis", "Relance requise auprès des contributeurs", "neutral"], ["2", "En attente de décision", "Synthèse et avis disponibles", "success"]].map(([n,l,d,t]) => <button key={l} onClick={() => go("dossiers")} className="flex w-full items-center gap-4 px-5 py-4 text-left hover:bg-muted/50"><span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-secondary text-sm font-bold text-secondary-foreground">{n}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{l}</span><span className="block truncate text-xs text-muted-foreground">{d}</span></span><Status tone={t as Tone}>À traiter</Status><ChevronRight className="size-4 text-muted-foreground" /></button>)}
        </div>
      </Panel>
      <Panel><PanelTitle title="Situation du portefeuille" subtitle="Évolution depuis le trimestre précédent" /><div className="grid grid-cols-2 gap-px bg-border"><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Exposition totale</p><p className="mt-2 text-xl font-bold">684,2 M</p><p className="mt-1 flex items-center gap-1 text-xs text-success"><ArrowUpRight className="size-3" /> +4,2 %</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Note moyenne</p><p className="mt-2 text-xl font-bold">B+</p><p className="mt-1 text-xs text-muted-foreground">Stable</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Indicateurs en baisse</p><p className="mt-2 text-xl font-bold">8</p><p className="mt-1 flex items-center gap-1 text-xs text-destructive"><ArrowDownRight className="size-3" /> +2 clients</p></div><div className="bg-card p-5"><p className="text-xs text-muted-foreground">Données à jour</p><p className="mt-2 text-xl font-bold">91 %</p><Progress value={91} className="mt-2" /></div></div></Panel>
    </div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]">
      <Panel><PanelTitle title="Alertes prioritaires" action={<Button variant="ghost" size="sm" onClick={() => go("alertes")}>Centre d’alertes <ArrowRight /></Button>} /><div className="divide-y divide-border">{alerts.slice(0,3).map(a => <button onClick={() => go("alertes")} key={a.label} className="flex w-full items-center gap-4 px-5 py-3.5 text-left hover:bg-muted/50"><span className={cn("size-2 rounded-full", a.tone === "danger" ? "bg-destructive" : "bg-warning")} /><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{a.client}</span><span className="block truncate text-xs text-muted-foreground">{a.label}</span></span><span className="text-xs font-semibold">{a.metric}</span></button>)}</div></Panel>
      <Panel><PanelTitle title="Activité récente" /><div className="space-y-4 p-5">{[["Données financières importées", "Nova Industrie · il y a 34 min"], ["Avis risque soumis", "Atlas Microfinance · il y a 2 h"], ["Décision enregistrée", "Kenz Textile · hier à 17:42"]].map(([a,b],i)=><div key={a} className="flex gap-3"><span className="mt-0.5 flex size-7 items-center justify-center rounded-full bg-secondary text-primary">{i===0?<Upload className="size-3.5"/>:<Check className="size-3.5"/>}</span><div><p className="text-sm font-medium">{a}</p><p className="text-xs text-muted-foreground">{b}</p></div></div>)}</div></Panel>
    </div></>;
}

function Dossiers({ open }: { open: () => void }) {
  return <><PageHeader eyebrow="Due diligence" title="Dossiers" description="Pilotez les analyses en cours, de la collecte jusqu’à la décision." action={<Button onClick={open}><Plus /> Nouveau dossier</Button>} />
    <Panel><div className="flex flex-col gap-3 border-b border-border p-4 lg:flex-row lg:items-center"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Rechercher un dossier ou une contrepartie…" /></div><Button variant="outline"><Filter /> Statut <ChevronDown /></Button><Button variant="outline"><SlidersHorizontal /> Plus de filtres</Button></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left"><thead><tr className="border-b border-border bg-muted/45 text-[11px] font-bold uppercase text-muted-foreground">{["Dossier / Contrepartie","Type","Demande","Étape actuelle","Risque","Progression","Dernière mise à jour","Responsable",""] .map(h=><th key={h} className="px-4 py-3">{h}</th>)}</tr></thead><tbody className="divide-y divide-border">{dossiers.map(d=><tr key={d.id} onClick={open} className="cursor-pointer text-sm hover:bg-muted/40"><td className="px-4 py-4"><p className="font-semibold">{d.name}</p><p className="text-xs text-muted-foreground">{d.id}</p></td><td className="px-4 py-4 text-muted-foreground">{d.type}</td><td className="px-4 py-4 font-medium">{d.amount}</td><td className="px-4 py-4"><Status tone={d.tone}>{d.stage}</Status></td><td className="px-4 py-4 font-bold">{d.risk}</td><td className="px-4 py-4"><div className="flex items-center gap-2"><Progress value={d.progress} className="w-20"/><span className="text-xs">{d.progress}%</span></div></td><td className="px-4 py-4 text-xs text-muted-foreground">{d.update}</td><td className="px-4 py-4 text-xs">{d.owner}</td><td className="px-4 py-4"><MoreHorizontal className="size-4"/></td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-border px-4 py-3 text-xs text-muted-foreground"><span>5 dossiers sur 28</span><div className="flex gap-1"><Button size="icon" variant="outline" disabled><ChevronLeft /></Button><Button size="icon" variant="outline"><ChevronRight /></Button></div></div>
    </Panel></>;
}

const steps = ["Information", "Données", "Questionnaire", "Analyse", "Évaluation", "Avis", "Décision"];
function Dossier({ back }: { back: () => void }) {
  const [tab, setTab] = useState("Analyse");
  return <><button onClick={back} className="mb-4 flex items-center gap-1 text-xs font-semibold text-muted-foreground hover:text-foreground"><ChevronLeft className="size-4"/> Retour aux dossiers</button>
    <div className="flex flex-col gap-4 border-b border-border pb-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-bold">Atlas Microfinance</h1><Status tone="warning">Analyse en cours</Status></div><p className="mt-1 text-sm text-muted-foreground">Institution de microfinance · DD-2026-084 · Demande de 18,5 M MAD</p></div><div className="min-w-52"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Progression globale</span><strong>72 %</strong></div><Progress value={72}/><p className="mt-2 text-right text-[11px] text-muted-foreground">Mis à jour aujourd’hui à 09:42</p></div></div>
    <div className="my-5 overflow-x-auto"><div className="flex min-w-[820px]">{steps.map((s,i)=><button key={s} onClick={()=>setTab(s)} className="group flex flex-1 items-center"><span className={cn("flex size-7 shrink-0 items-center justify-center rounded-full border text-xs font-bold", i<3?"border-success bg-success text-success-foreground":s===tab?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground")}>{i<3?<Check className="size-3.5"/>:i+1}</span><span className={cn("ml-2 text-xs font-semibold",s===tab?"text-primary":"text-muted-foreground")}>{s}</span>{i<steps.length-1&&<span className="mx-3 h-px flex-1 bg-border"/>}</button>)}</div></div>
    <div className="grid gap-5 xl:grid-cols-[1fr_280px]">{tab === "Information" ? <Information /> : tab === "Données" ? <FinancialData /> : tab === "Questionnaire" ? <Questionnaire /> : tab === "Évaluation" ? <Evaluation /> : tab === "Avis" ? <Opinions /> : tab === "Décision" ? <Decision /> : <Analysis />}
      <aside className="space-y-4"><Panel><PanelTitle title="Qualité des données"/><div className="p-5"><div className="mb-2 flex justify-between text-xs"><span>Complétude</span><strong>94 %</strong></div><Progress value={94}/><div className="mt-4 space-y-3 text-xs"><p className="flex items-center gap-2 text-success"><Check className="size-4"/> 47 points validés</p><p className="flex items-center gap-2 text-warning-foreground"><CircleAlert className="size-4"/> 3 à vérifier</p><p className="flex items-center gap-2 text-destructive"><X className="size-4"/> 2 données manquantes</p></div></div></Panel><Panel><PanelTitle title="Actions rapides"/><div className="grid gap-2 p-4"><Button variant="outline" className="justify-start"><FileText/> Voir les documents</Button><Button variant="outline" className="justify-start"><History/> Historique du dossier</Button><Button variant="outline" className="justify-start"><UserRound/> Affecter un contributeur</Button></div></Panel></aside>
    </div></>;
}

function Analysis() { const indicators=[['PAR30','5,8 %','4,1 %','+1,7 pts','warning'],['ROA','4,2 %','3,9 %','+0,3 pt','success'],['Ratio de solvabilité','18,5 %','18,1 %','+0,4 pt','success'],['Liquidité immédiate','22,8 %','24,4 %','−1,6 pt','neutral']]; return <Panel><PanelTitle title="Analyse financière" subtitle="Indicateurs calculés à partir des données validées du T2 2026" action={<Button variant="outline" size="sm"><Download/> Exporter</Button>}/><div className="grid gap-4 p-5 md:grid-cols-2">{indicators.map(([n,v,p,c,t],i)=><div key={n} className="rounded-md border border-border p-4"><div className="flex justify-between"><div><p className="text-xs text-muted-foreground">{n}</p><p className="mt-1 text-2xl font-bold">{v}</p></div><Status tone={t as Tone}>{t==='warning'?'À surveiller':'Satisfaisant'}</Status></div><div className="mt-4 flex items-end justify-between"><div className="text-xs text-muted-foreground">Période précédente <strong className="text-foreground">{p}</strong><br/>Variation <strong className={c.startsWith('+')&&i!==0?'text-success':i===0?'text-destructive':'text-foreground'}>{c}</strong></div><div className="flex h-12 items-end gap-1">{[32,44,38,55,50,70].map((h,j)=><span key={j} className={cn("w-2 rounded-sm",j===5?"bg-primary":"bg-secondary")} style={{height:`${h}%`}}/>)}</div></div></div>)}</div><div className="border-t border-border p-5"><h3 className="text-sm font-semibold">Tendance historique — PAR30</h3><div className="mt-4 flex h-28 items-end gap-3 rounded-md bg-muted/40 px-5 pt-5">{[3.4,3.7,4.1,4.4,4.9,5.8].map((v,i)=><div key={v} className="flex flex-1 flex-col items-center gap-2"><span className="text-[10px] font-semibold">{v}%</span><span className={cn("w-full max-w-12 rounded-t-sm",i===5?"bg-destructive":"bg-primary/55")} style={{height:`${v*10}px`}}/><span className="text-[10px] text-muted-foreground">T{i+1}</span></div>)}</div></div></Panel> }
function Information(){return <Panel><PanelTitle title="Informations de la contrepartie"/><div className="grid gap-6 p-5 md:grid-cols-2"><InfoBlock title="Informations générales" rows={[["Raison sociale","Atlas Microfinance SA"],["Activité","Microfinance et inclusion financière"],["Localisation","Rabat, Maroc"],["Date de création","12 mars 2008"],["Taille","412 collaborateurs"]]}/><InfoBlock title="Gouvernance" rows={[["Direction générale","Nadia Benjelloun"],["Président du conseil","Karim El Fassi"],["Actionnaire principal","Holding Atlas (64 %)"]]}/><div className="md:col-span-2"><h3 className="mb-3 text-sm font-semibold">Documents requis</h3><div className="grid gap-2 md:grid-cols-3">{[["États financiers 2025","Disponible","success"],["Documents juridiques","Disponible","success"],["Rapport d’audit","Manquant","danger"]].map(([a,b,t])=><div className="flex items-center justify-between rounded-md border border-border p-3" key={a}><span className="text-xs font-medium">{a}</span><Status tone={t as Tone}>{b}</Status></div>)}</div></div></div></Panel>}
function FinancialData(){return <Panel><PanelTitle title="Données financières" subtitle="Période de reporting : T2 2026" action={<div className="flex gap-2"><Button variant="outline" size="sm"><Upload/>Importer</Button><Button size="sm">Saisie manuelle</Button></div>}/><div className="p-5"><div className="mb-5 rounded-md bg-info-soft p-4"><div className="flex justify-between text-sm"><strong>82 % des données requises complétées</strong><span>41 / 50</span></div><Progress value={82} className="mt-3"/></div><div className="grid gap-3 md:grid-cols-2">{[["Bilan","18 / 18 champs","Validé"],["Compte de résultat","12 / 14 champs","À compléter"],["Flux de trésorerie","7 / 9 champs","À vérifier"],["Données métier","4 / 9 champs","Incomplet"]].map(([a,b,c])=><div key={a} className="rounded-md border border-border p-4"><div className="flex justify-between"><FileCheck2 className="size-5 text-primary"/><Status tone={c==='Validé'?'success':'warning'}>{c}</Status></div><h3 className="mt-4 text-sm font-semibold">{a}</h3><p className="mt-1 text-xs text-muted-foreground">{b}</p></div>)}</div><div className="mt-4 rounded-md border border-destructive/25 bg-danger-soft p-4 text-sm"><strong>Erreur de rapprochement</strong><p className="mt-1 text-xs text-muted-foreground">Le total de l’actif ne correspond pas au passif + capitaux propres.</p></div></div></Panel>}
function Questionnaire(){return <Panel><PanelTitle title="Questionnaire d’évaluation" subtitle="24 réponses sur 28 · 3 questions obligatoires sans réponse"/><div className="divide-y divide-border">{[["Gouvernance et contrôle interne",92],["Gestion des risques",78],["Stratégie et modèle économique",86]].map(([a,p])=><div key={a} className="p-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold">{a}</h3><span className="text-xs font-bold">{p}%</span></div><Progress value={p as number} className="mt-2"/></div>)}<div className="p-5"><p className="text-xs font-bold text-destructive">QUESTION OBLIGATOIRE</p><p className="mt-2 text-sm font-semibold">Existe-t-il une politique formelle de gestion des risques ?</p><div className="mt-3 flex gap-2">{["Oui","Non","Partiellement"].map(x=><Button key={x} variant="outline" size="sm">{x}</Button>)}</div><textarea className="mt-3 min-h-20 w-full rounded-md border border-input bg-background p-3 text-sm outline-none focus:ring-1 focus:ring-ring" placeholder="Ajouter un commentaire…"/></div></div></Panel>}
function Evaluation(){return <Panel><PanelTitle title="Évaluation du risque" subtitle="Résultat expliqué selon la méthodologie active"/><div className="grid gap-5 p-5 md:grid-cols-[220px_1fr]"><div className="rounded-md bg-secondary p-6 text-center"><p className="text-xs font-semibold text-muted-foreground">NOTE GLOBALE</p><p className="mt-3 text-5xl font-bold text-primary">B+</p><p className="mt-2 text-sm font-semibold">72 / 100</p><Status tone="warning">Risque modéré</Status></div><div className="space-y-4">{[["Solidité financière",78],["Qualité du portefeuille",65],["Gouvernance",81],["Liquidité",74]].map(([a,v])=><div key={a}><div className="mb-1 flex justify-between text-xs"><span>{a}</span><strong>{v}/100</strong></div><Progress value={v as number}/></div>)}</div></div><div className="grid gap-px border-t border-border bg-border md:grid-cols-2"><div className="bg-card p-5"><h3 className="text-sm font-semibold text-success">Facteurs positifs</h3><ul className="mt-3 space-y-2 text-xs">{["Solvabilité supérieure au seuil","Croissance soutenue du portefeuille","Liquidité adéquate"].map(x=><li key={x} className="flex gap-2"><Check className="size-4 text-success"/>{x}</li>)}</ul></div><div className="bg-card p-5"><h3 className="text-sm font-semibold text-destructive">Facteurs de risque</h3><ul className="mt-3 space-y-2 text-xs">{["Dégradation de la qualité du portefeuille","Concentration géographique élevée","Rentabilité sous pression"].map(x=><li key={x} className="flex gap-2"><AlertTriangle className="size-4 text-destructive"/>{x}</li>)}</ul></div></div></Panel>}
function Opinions(){return <Panel><PanelTitle title="Avis des parties prenantes" subtitle="2 favorables · 1 favorable avec conditions · 1 en attente"/><div className="divide-y divide-border">{[["S. El Amrani","Analyste","Favorable","success"],["N. Berrada","Direction des risques","Favorable avec conditions","warning"],["A. Chraïbi","Juridique","En cours","info"],["Comité de crédit","Direction","En attente","neutral"]].map(([n,r,s,t])=><div key={n} className="flex items-center gap-4 p-5"><span className="flex size-9 items-center justify-center rounded-full bg-secondary text-xs font-bold">{n.split(' ').map(x=>x[0]).join('')}</span><div className="flex-1"><p className="text-sm font-semibold">{n}</p><p className="text-xs text-muted-foreground">{r}</p></div><Status tone={t as Tone}>{s}</Status></div>)}</div></Panel>}
function Decision(){return <Panel><PanelTitle title="Décision finale" subtitle="Tous les éléments requis sont disponibles"/><div className="p-5"><div className="grid gap-3 md:grid-cols-4">{[["Approuver","success"],["Avec conditions","warning"],["Rejeter","danger"],["Complément requis","info"]].map(([a,t])=><button key={a} className={cn("rounded-md border p-4 text-left text-sm font-semibold transition hover:border-primary",t==='success'&&"bg-success/5",t==='warning'&&"bg-warning/5",t==='danger'&&"bg-danger-soft")}>{a}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2"><label className="text-xs font-semibold">Montant approuvé<Input className="mt-2" defaultValue="18 500 000 MAD"/></label><label className="text-xs font-semibold">Conditions<Input className="mt-2" placeholder="Saisir les conditions…"/></label></div><label className="mt-4 block text-xs font-semibold">Motivation de la décision<textarea className="mt-2 min-h-24 w-full rounded-md border border-input bg-background p-3 text-sm outline-none focus:ring-1 focus:ring-ring" placeholder="Documenter la décision…"/></label><div className="mt-5 flex justify-end"><Button>Enregistrer la décision <ArrowRight/></Button></div></div></Panel>}
function InfoBlock({title,rows}:{title:string;rows:string[][]}){return <div><h3 className="mb-3 text-sm font-semibold">{title}</h3><dl className="divide-y divide-border rounded-md border border-border">{rows.map(([a,b])=><div key={a} className="flex justify-between gap-4 p-3 text-xs"><dt className="text-muted-foreground">{a}</dt><dd className="text-right font-medium">{b}</dd></div>)}</dl></div>}

function Portfolio({ open }: { open: () => void }) { const clients=[['Atlas Microfinance','IMF','42,5 M','B+','5,8 % PAR30','2'],['Nova Industrie','TPME','31,8 M','A-','1,6x DSCR','0'],['Sahara Agro','TPME','24,2 M','B','−8,4 % CA','1'],['Tamwil Coopérative','Coopérative','18,7 M','B','9,2 % impayés','3']]; return <><PageHeader eyebrow="Suivi" title="Portefeuille sous surveillance" description="Vue consolidée des risques, expositions et données de reporting." action={<Button variant="outline"><Download/> Exporter</Button>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Clients suivis" value="124" detail="8 segments actifs" icon={Users}/><Metric label="Exposition totale" value="684,2 M" detail="MAD · +4,2 % sur 12 mois" icon={BriefcaseBusiness} tone="success"/><Metric label="Performance en baisse" value="8" detail="6,5 % du portefeuille" icon={TrendingDown} tone="warning"/><Metric label="Covenants rompus" value="5" detail="3 clients concernés" icon={ShieldAlert} tone="danger"/></div><Panel className="mt-5"><PanelTitle title="Clients suivis" action={<Button variant="outline" size="sm"><Filter/>Filtrer</Button>}/><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="bg-muted/45 text-[11px] uppercase text-muted-foreground">{['Client','Type','Exposition','Note','Indicateur principal','Fraîcheur','Alertes'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody className="divide-y divide-border">{clients.map((c,i)=><tr key={c[0]} onClick={open} className="cursor-pointer hover:bg-muted/40"><td className="px-4 py-4 font-semibold">{c[0]}</td><td className="px-4 py-4 text-muted-foreground">{c[1]}</td><td className="px-4 py-4 font-medium">{c[2]}</td><td className="px-4 py-4"><Status tone={i===0?'warning':'success'}>{c[3]}</Status></td><td className="px-4 py-4">{c[4]}</td><td className="px-4 py-4"><Status tone={i===2?'danger':'success'}>{i===2?'En retard':'À jour'}</Status></td><td className="px-4 py-4 font-bold">{c[5]}</td></tr>)}</tbody></table></div></Panel></> }
function Collection(){return <><PageHeader eyebrow="Opérations" title="Collecte périodique" description="Contrôlez les imports automatiques et les soumissions attendues." action={<Button><Upload/> Import manuel</Button>}/><div className="grid gap-3 md:grid-cols-4"><Metric label="Clients traités" value="124" detail="Dernière exécution à 06:00" icon={Building2}/><Metric label="Imports réussis" value="118" detail="95,2 % de réussite" icon={Check} tone="success"/><Metric label="Erreurs" value="4" detail="À corriger ou relancer" icon={CircleAlert} tone="danger"/><Metric label="Dossiers manquants" value="2" detail="Relance nécessaire" icon={Clock3} tone="warning"/></div><Panel className="mt-5"><PanelTitle title="Historique des exécutions" action={<Button variant="outline" size="sm"><RefreshCw/>Relancer</Button>}/><div className="divide-y divide-border">{[['18 sept. 2026 · 06:00','124','118','4','2'],['17 sept. 2026 · 06:00','122','120','1','1'],['16 sept. 2026 · 06:00','122','119','2','1']].map(r=><div key={r[0]} className="grid grid-cols-5 gap-4 p-4 text-sm"><strong>{r[0]}</strong><span>{r[1]} traités</span><span className="text-success">{r[2]} réussis</span><span className="text-destructive">{r[3]} erreurs</span><span className="text-warning-foreground">{r[4]} manquants</span></div>)}</div></Panel></>}
function Alerts(){return <><PageHeader eyebrow="Risques" title="Alertes & covenants" description="Priorisez, instruisez et clôturez les événements de risque."/><div className="grid gap-3 sm:grid-cols-4"><Metric label="Critiques" value="2" detail="Action immédiate" icon={ShieldAlert} tone="danger"/><Metric label="Élevées" value="6" detail="À traiter sous 48 h" icon={AlertTriangle} tone="warning"/><Metric label="Moyennes" value="4" detail="Sous surveillance" icon={CircleAlert}/><Metric label="Résolues" value="18" detail="Sur les 30 derniers jours" icon={Check} tone="success"/></div><Panel className="mt-5"><PanelTitle title="Alertes actives" action={<Button variant="outline" size="sm"><Filter/>Filtrer</Button>}/><div className="divide-y divide-border">{alerts.map(a=><div key={a.label} className="flex flex-col gap-3 p-5 md:flex-row md:items-center"><span className={cn("flex size-9 items-center justify-center rounded-md",a.tone==='danger'?'bg-danger-soft text-destructive':'bg-warning/15 text-warning-foreground')}><AlertTriangle className="size-4"/></span><div className="flex-1"><p className="text-sm font-semibold">{a.client}</p><p className="text-xs text-muted-foreground">{a.label} · Détectée le {a.date}</p></div><strong className="text-sm">{a.metric}</strong><Status tone={a.tone}>{a.severity}</Status><Button variant="outline" size="sm">Examiner</Button></div>)}</div></Panel></>}
function Comparison(){return <><PageHeader eyebrow="Analyse" title="Comparaison" description="Comparez uniquement les indicateurs compatibles entre périodes ou contreparties."/><Panel><div className="grid gap-3 border-b border-border p-4 md:grid-cols-3"><Button variant="outline" className="justify-between">Clients multiples <ChevronDown/></Button><Button variant="outline" className="justify-between">T2 2026 <ChevronDown/></Button><Button variant="outline" className="justify-between">Indicateurs financiers <ChevronDown/></Button></div><PanelTitle title="Comparaison des pairs" subtitle="Institutions de microfinance · T2 2026"/><div className="overflow-x-auto p-5"><table className="w-full min-w-[620px] text-sm"><thead><tr className="text-left text-xs text-muted-foreground"><th className="py-3">Indicateur</th><th>Atlas Microfinance</th><th>Amana Finance</th><th>Al Baraka Microcrédit</th><th>Moyenne</th></tr></thead><tbody className="divide-y divide-border">{[['PAR30','5,8 %','3,9 %','4,4 %','4,7 %'],['ROA','4,2 %','3,1 %','4,8 %','3,9 %'],['Solvabilité','18,5 %','20,1 %','16,7 %','18,4 %'],['Croissance','12,4 %','8,7 %','10,1 %','10,4 %']].map(r=><tr key={r[0]}><td className="py-4 font-semibold">{r[0]}</td>{r.slice(1).map((x,i)=><td key={i} className={cn(i===0&&r[0]==='PAR30'&&"font-bold text-destructive")}>{x}</td>)}</tr>)}</tbody></table></div></Panel></>}
function Reports(){return <><PageHeader eyebrow="Reporting" title="Rapports & benchmarking" description="Générez vos livrables à partir des modèles validés." action={<Button><Plus/>Générer un rapport</Button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{[['Rapport de due diligence','Atlas Microfinance · DD-2026-084','Mis à jour aujourd’hui'],['Analyse financière','Portefeuille IMF · T2 2026','Généré le 17 sept.'],['Rapport de suivi','Portefeuille consolidé · Août 2026','Généré le 12 sept.'],['Évaluation des risques','Nova Industrie · DD-2026-081','Généré le 10 sept.'],['Benchmark sectoriel','TPME industrielles · T2 2026','Généré le 8 sept.'],['Rapport comité de crédit','Session du 22 septembre','Brouillon']].map(([a,b,c])=><Panel key={a} className="p-5"><div className="flex justify-between"><span className="flex size-9 items-center justify-center rounded-md bg-info-soft text-primary"><FileBarChart className="size-4"/></span><Button variant="ghost" size="icon"><MoreHorizontal/></Button></div><h3 className="mt-5 text-sm font-semibold">{a}</h3><p className="mt-1 text-xs text-muted-foreground">{b}</p><div className="mt-5 flex items-center justify-between border-t border-border pt-4"><span className="text-[11px] text-muted-foreground">{c}</span><Button variant="ghost" size="sm"><Download/>PDF</Button></div></Panel>)}</div></>}

export function FinancialWorkspace() {
  const [view,setView]=useState<View>("dashboard"); const [collapsed,setCollapsed]=useState(false); const [mobileOpen,setMobileOpen]=useState(false);
  const go=(v:View)=>{setView(v);setMobileOpen(false)};
  return <div className="min-h-screen bg-background text-foreground"><aside className={cn("fixed inset-y-0 left-0 z-40 flex flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground transition-all",collapsed?"w-[68px]":"w-60",mobileOpen?"translate-x-0":"max-lg:-translate-x-full")}><div className="flex h-16 items-center gap-3 border-b border-sidebar-border px-4"><span className="flex size-9 shrink-0 items-center justify-center rounded-md bg-sidebar-primary font-bold text-primary-foreground">F</span>{!collapsed&&<div><p className="text-sm font-bold text-sidebar-accent-foreground">FinScope</p><p className="text-[10px] text-sidebar-foreground/65">ANALYSE & RISQUES</p></div>}<button className="ml-auto lg:hidden" onClick={()=>setMobileOpen(false)} aria-label="Fermer le menu"><X className="size-5"/></button></div><nav className="flex-1 overflow-y-auto px-2 py-4">{nav.map((group,g)=><div key={g} className="mb-4">{group.group&&!collapsed&&<p className="mb-1 px-3 text-[10px] font-bold text-sidebar-foreground/45">{group.group}</p>}<div className="space-y-0.5">{group.items.map((item,i)=><button key={`${item.label}-${i}`} title={item.label} onClick={()=>go(item.id)} className={cn("flex h-10 w-full items-center gap-3 rounded-md px-3 text-sm transition",view===item.id?"bg-sidebar-accent font-semibold text-sidebar-accent-foreground":"text-sidebar-foreground/75 hover:bg-sidebar-accent/60 hover:text-sidebar-accent-foreground")}><item.icon className="size-4 shrink-0"/>{!collapsed&&<span className="truncate">{item.label}</span>}{item.id==='alertes'&&!collapsed&&<span className="ml-auto rounded bg-destructive px-1.5 py-0.5 text-[10px] font-bold text-destructive-foreground">12</span>}</button>)}</div></div>)}</nav><div className="border-t border-sidebar-border p-3"><button onClick={()=>setCollapsed(!collapsed)} className="hidden w-full items-center gap-3 rounded-md px-3 py-2 text-xs text-sidebar-foreground/70 hover:bg-sidebar-accent lg:flex">{collapsed?<PanelLeftOpen className="size-4"/>:<><PanelLeftClose className="size-4"/>Réduire</>}</button></div></aside>{mobileOpen&&<button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" onClick={()=>setMobileOpen(false)} aria-label="Fermer"/>}
    <div className={cn("transition-all",collapsed?"lg:pl-[68px]":"lg:pl-60")}><header className="sticky top-0 z-20 flex h-16 items-center border-b border-border bg-card/95 px-4 backdrop-blur md:px-6"><Button variant="ghost" size="icon" className="mr-2 lg:hidden" onClick={()=>setMobileOpen(true)}><Menu/></Button><div className="relative hidden w-full max-w-md md:block"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="border-transparent bg-muted pl-9 shadow-none" placeholder="Rechercher un client, un dossier, un indicateur…"/></div><div className="ml-auto flex items-center gap-2"><Button variant="ghost" size="icon" title="Aide"><HelpCircle/></Button><Button variant="ghost" size="icon" className="relative" title="Notifications"><Bell/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-destructive"/></Button><div className="mx-1 h-6 w-px bg-border"/><button className="hidden items-center gap-2 rounded-md px-2 py-1.5 hover:bg-muted sm:flex"><span className="flex size-8 items-center justify-center rounded-full bg-primary text-xs font-bold text-primary-foreground">SE</span><span className="text-left"><span className="block text-xs font-semibold">Samira El Amrani</span><span className="block text-[10px] text-muted-foreground">Analyste risques</span></span><ChevronDown className="size-3 text-muted-foreground"/></button></div></header><main className="mx-auto max-w-[1500px] p-4 md:p-6 lg:p-8">{view==='dashboard'?<Dashboard go={go}/>:view==='dossiers'?<Dossiers open={()=>go('dossier')}/>:view==='dossier'?<Dossier back={()=>go('dossiers')}/>:view==='portfolio'?<Portfolio open={()=>go('dossier')}/>:view==='collecte'?<Collection/>:view==='alertes'?<Alerts/>:view==='comparaison'?<Comparison/>:<Reports/>}</main></div>
  </div>;
}